### ISSUE TITLE
Wild Command

### ISSUE THREAD

**Issue by ARandomGuy69** [CanyonNetwork/XOSurvival-Core#1]
**For the RTP portal to work, yall need to make an RTP command. That has to RTP people within 50k in "customworld".**

**Comment by FroostySnoowman** [comment]
Working on this feature. Hoping to have it done in a little bit.

**Comment by FroostySnoowman** [comment]
This is now done. You can use "/wildc" as a command in game. Soon I'll be replacing the command with the GUI and only have the GUI to work so you can choose where you teleport to.
